### ISSUE TITLE
How to replace FocalLoss in testing phase?

### ISSUE THREAD

**Issue by SingL3** [Longqi-S/Focal-Loss#4]
In training phase, we use SoftmaxWithLoss Layer and replace it with Softmax in testing. If I use FocalLoss in training, is it still replaced by Softmax?

**Comment by Longqi-S** [comment]
@SingL3 Yes, softmax is replaced by focal loss in training phase.

**Comment by SingL3** [comment]
@Longqi-S I mean when testing, I just use Softmax to replace FocalLoss in training, right?

**Comment by Longqi-S** [comment]
@SingL3 yes, you are right~

**Comment by SingL3** [comment]
Thank you!
